name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Make tests
        run: | 
          make tidy
          make test
